name: promptsage
region: nyc
static_sites:
  - name: promptsage
    github:
      repo: nma124/promptsage
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    envs:
      - key: VITE_GOOGLE_API_KEY
        scope: BUILD_TIME
        type: SECRET
    catchall_document: index.html
